project:
  type: website
  output-dir: _site #for the logo to appear

website:
  favicon: /images/dragon.svg
  title: ""
  page-footer: "Made with ðŸ’š and Quarto"
  announcement:
    content: "**NEW (08/03)** - [**Hands-on Exercise 8**](https://cathyc.netlify.app/honds-on_ex/hands-on_ex08_1) are published!"
    position: below-navbar
    icon: rocket-takeoff-fill
    
  navbar:
    logo: "images/dino.png"
    right:
    - href: index.qmd
      text: "![](/images/house.svg)"
    - href: about.qmd
      text: "![](/images/person.svg)"

    left: 
    - text: "**Hands-on Exercise**"
      menu:
      - text: "Hands-on_Ex00"
        href: Hands-on_Ex/Hands-on_Ex00/Hands-on_Ex00.qmd
      - text: "1 A Layered Grammar of Graphics: ggplot2 methods."
        href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd
      - text: "2 Beyond ggplot2 Fundamentals"
        href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd
      - text: "3_1 Interactive Data Visualisation with R"
        href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_1.qmd
      - text: "3_2 Animated Statistical Graphics with R"
        href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_2.qmd
      - text: "4_1 Visualising Distribution"
        href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_1.qmd
      - text: "4_2 Visual Statistical Analysis"
        href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_2.qmd
      - text: "4_3 Visualising Uncertainty"
        href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_3.qmd
      - text: "4_4 Building Funnel Plot with R"
        href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_4.qmd
      - text: "5_1 Building Ternary Plot with R"
        href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_1.qmd
      - text: "5_2 Visual Correlation Analysis"
        href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_2.qmd
      - text: "5_3 Visual Multivariate Analysis with Heatmap"
        href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_3.qmd
      - text: "5_4 Visual Multivariate Analysis with Parallel Coordinates Plot"
        href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_4.qmd
      - text: "5_5 Treemap Visualisation with R"
        href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_5.qmd
      - text: "7 Visualising time-oriented data"
        href: Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.qmd
       - text: "Hands-on Exercise 8-1"
         href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08_1.qmd
       - text: "Hands-on Exercise 8-2"
         href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08_2.qmd
       - text: "Hands-on Exercise 8-3"
         href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08_3.qmd
      # - text: "Hands-on Exercise 9"
      #   href: Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.qmd
    - text: "**In-class Exercise**"
      menu:
      - text: "In-class Exercise 1"
        href: In-class_Ex/In-class_Ex01.qmd
      - text: "In-class Exercise 2"
        href: In-class_Ex/In-class_Ex02.qmd
      - text: "In-class Exercise 3"
        href: In-class_Ex/In-class_Ex03.qmd
      - text: "In-class Exercise 4"
        href: In-class_Ex/In-class_Ex04.qmd
      - text: "In-class Exercise 5"
        href: In-class_Ex/In-class_Ex05.qmd
      - text: "In-class Exercise 7"
        href: In-class_Ex/In-class_Ex07.qmd       
        
    - text: "**Take-home Exercise**"
      menu: 
      - text: "Take-home Exercise 1"
        href: Take-home_Ex/Take-home_Ex01.qmd
      - text: "Take-home Exercise 2"
        href: Take-home_Ex/Take-home_Ex02.qmd
      - text: "Take-home Exercise 3"


  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Hands-on Exercise"
        href: Hands-on_Ex/Hands-on_Ex00/Hands-on_Ex00.html
        contents:
          - text: "Hands-on_Ex00"
            href: Hands-on_Ex/Hands-on_Ex00/Hands-on_Ex00.html
          - text: "Hands-on Exercise 0"
            href: Hands-on_Ex/Hands-on_Ex00/Hands-on_Ex00.qmd
          - text: "Hands-on Exercise 1"
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd
          - text: "Hands-on Exercise 2"
            href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd
          - text: "Hands-on Exercise 3-1"
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_1.qmd
          - text: "Hands-on Exercise 3-2"
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_2.qmd
          - text: "Hands-on Exercise 4-1"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_1.qmd
          - text: "Hands-on Exercise 4-2"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_2.qmd
          - text: "Hands-on Exercise 4-3"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_3.qmd
          - text: "Hands-on Exercise 4-4"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_4.qmd
          - text: "Hands-on Exercise 5-1"
            href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_1.qmd
          - text: "Hands-on Exercise 5-2"
            href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_2.qmd
          - text: "Hands-on Exercise 5-3"
            href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_3.qmd
          - text: "Hands-on Exercise 5-4"
            href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_4.qmd
          - text: "Hands-on Exercise 5-5"
            href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_5.qmd
          - text: "Hands-on Exercise 7"
            href: Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.qmd
          - text: "Hands-on Exercise 8-1"
            href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08_1.qmd
          - text: "Hands-on Exercise 8-2"
            href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08_2.qmd
          - text: "Hands-on Exercise 8-3"
            href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08_3.qmd
            
      - section: "In-class Exercise"
        contents:
          - text: "In-class_Ex1"
            href: In-class_Ex/In-class_Ex01.html
          - text: "In-class_Ex2"
            href: In-class_Ex/In-class_Ex02.html
          - text: "In-class_Ex3"
            href: In-class_Ex/In-class_Ex03.html
          - text: "In-class_Ex4"
            href: In-class_Ex/In-class_Ex04.html
          - text: "In-class_Ex5"
            href: In-class_Ex/In-class_Ex05.qmd
          
      - section: "Take-home Exercise"
        contents:
          - text: "Take-home_Ex01"
            href: Take-home_Ex/Take-home_Ex01.html
          - text: "Take-home_Ex02"
            href: Take-home_Ex/Take-home_Ex02.html
      - text: "About"
        href: about.qmd

format:
  html:
    linkcolor: "#db7093"
    theme:
      - cosmo
      - brand
    css: styles.css
    logo: dino.png
    toc: true

editor: visual

brand:
  color:
    background: "#ebf5fb"
    

